/* Editorial guidance, separate from analytical rules and project validation. */
(function (global) {
    'use strict';
    const references = {
        framework: { title: 'Gale et al. (2013). Using the Framework Method', url: 'https://doi.org/10.1186/1471-2288-13-117' },
        thematic: { title: 'Braun y Clarke. Understanding thematic analysis', url: 'https://www.thematicanalysis.net/understanding-ta/' },
        typology: { title: 'Kluge (2000). Empirically Grounded Construction of Types and Typologies', url: 'https://doi.org/10.17169/fqs-1.1.1124' },
        mixed: { title: 'Guetterman, Fetters y Creswell (2015). Integration Through Joint Displays', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4639381/' },
        longitudinal: { title: 'Grossoehme y Lipstein (2016). Analyzing longitudinal qualitative data', url: 'https://doi.org/10.1186/s13104-016-1954-1' },
        grounded: { title: 'Chun Tie, Birks y Francis (2019). Grounded theory research', url: 'https://doi.org/10.1177/2050312118822927' },
        content: { title: 'Mayring (2000). Qualitative Content Analysis', url: 'https://www.qualitative-research.net/index.php/fqs/article/view/1089/2386' }
    };
    // The mapping below is an explicit software-design recommendation, not a
    // validated measure of methodological suitability or a claim of exclusivity.
    const approaches = {
        unspecified: { label: 'Sin enfoque especificado', rationale: 'Comienza por la pregunta de investigación y la unidad de análisis. No hay una herramienta universalmente preferible.', caution: 'Las sugerencias no evalúan la calidad del diseño.', picks: [['source-category', 'Revisar qué evidencia tiene cada fuente.'], ['evidence', 'Identificar qué necesita revisión.']], refs: [] },
        thematic: { label: 'Análisis temático', rationale: 'Puede ayudarte a explorar patrones de significado y contrastarlos con pasajes y memos. Existen distintas variantes de análisis temático.', caution: 'En la variante reflexiva, frecuencia y acuerdo entre codificadores no definen por sí solos un tema. La red de copresencia de esta app no es un mapa temático interpretativo.', picks: [['evidence', 'Volver a fragmentos y revisar interpretaciones.'], ['case-category', 'Contrastar patrones entre casos sin reducir los temas a conteos.']], refs: ['thematic'] },
        'grounded-theory': { label: 'Teoría fundamentada', rationale: 'La comparación y los memos pueden apoyar el desarrollo progresivo de categorías y relaciones conceptuales.', caution: 'Una red calculada no genera teoría, no decide muestreo teórico ni demuestra saturación. Las variantes de teoría fundamentada requieren decisiones propias.', picks: [['case-category', 'Comparar evidencia entre casos y revisar categorías.'], ['network', 'Explorar vínculos como hipótesis que requieren justificación en memos.']], refs: ['grounded'] },
        'content-analysis': { label: 'Análisis de contenido', rationale: 'Las matrices ayudan a revisar la aplicación de categorías definidas con criterios explícitos.', caution: 'Un recuento de asignaciones no representa automáticamente personas, prevalencia ni relevancia. Documenta unidad y reglas de codificación.', picks: [['source-category', 'Examinar la distribución por fuente.'], ['case-code', 'Revisar el libro de códigos por caso.'], ['comparison', 'Comparar grupos considerando su composición.']], refs: ['content'] },
        'framework-analysis': { label: 'Framework Analysis', rationale: 'La organización por casos y categorías facilita comparaciones conservando el contexto de cada caso.', caution: 'Las celdas numéricas de esta app no sustituyen las síntesis interpretativas de una matriz Framework; completa la lectura con evidencia y memos.', picks: [['case-category', 'Comparar categorías dentro de un caso y entre casos.'], ['joint', 'Reunir fragmentos, memos y recuentos para apoyar las síntesis.']], refs: ['framework'] },
        'case-study': { label: 'Estudio de caso', rationale: 'Como orientación de uso de la app, prioriza el contexto del caso, sus fuentes y los contrastes interpretados.', caution: 'Define primero qué constituye un caso. Una fuente no equivale necesariamente a un caso; varias fuentes pueden pertenecer a uno.', picks: [['source-category', 'Contrastar fuentes dentro del caso.'], ['case-category', 'Comparar casos cuando el diseño lo justifica.'], ['evidence', 'Examinar el respaldo y documentar discrepancias.']], refs: ['framework'] },
        'narrative-discourse': { label: 'Análisis narrativo o discursivo', rationale: 'El selector reúne tradiciones diferentes. Como apoyo de organización, prioriza la lectura situada de relatos, secuencias y usos del lenguaje.', caution: 'Una trayectoria de puntuaciones no analiza la estructura narrativa ni las posiciones discursivas. Vuelve a la fuente completa; estas herramientas no realizan ese análisis.', picks: [['source-category', 'Localizar pasajes sin perder la fuente completa.'], ['evidence', 'Revisar fragmentos y anotar contexto e interpretación.']], refs: [] },
        visual: { label: 'Análisis visual', rationale: 'Como orientación de uso, compara regiones codificadas conservando la imagen, su producción y su contexto.', caution: 'Ni OCR ni recuentos de regiones constituyen una interpretación visual. Dos regiones pueden tener significados distintos aunque compartan categoría.', picks: [['source-category', 'Localizar categorías en las fuentes visuales.'], ['evidence', 'Revisar regiones en la imagen original y registrar memos.']], refs: [] },
        mixed: { label: 'Diseño cualitativo mixto', rationale: 'Si el diseño combina componentes cualitativos y cuantitativos con integración explícita, un Joint Display puede ayudar a relacionar resultados.', caution: 'El selector no acredita un diseño de métodos mixtos. La tabla de esta app combina codificaciones, porcentajes y memos; por sí sola no integra una base cuantitativa independiente.', picks: [['joint', 'Confrontar evidencia y resultados para construir una interpretación integrada.'], ['comparison', 'Explorar contrastes entre grupos antes de interpretarlos.']], refs: ['mixed'] },
        other: { label: 'Otro enfoque', rationale: 'Explicita tu enfoque, preguntas y criterios. La app no puede deducirlos a partir de su nombre.', caution: 'Estas son opciones generales de exploración, no una recomendación específica para tu enfoque personalizado.', picks: [['source-category', 'Revisar fuentes y su evidencia.'], ['evidence', 'Documentar interpretaciones y límites.']], refs: [] }
    };
    const concepts = {
        'case-category': ['¿Qué comparten los casos y qué diferencia sus experiencias?', 'Comparación dentro de cada caso y entre casos mediante categorías compartidas.', 'Habitual como apoyo a Framework Analysis y comparación de casos; también puede servir a análisis de contenido o temático con criterios explícitos.', 'Si Ana y Luis tienen Participación, lee cómo aparece en cada uno: una puede describir decisión compartida y el otro asistencia sin voz. La misma presencia puede esconder significados distintos.', ['framework']],
        'case-code': ['¿Se está aplicando cada código de manera comparable entre casos?', 'Organización de evidencia mediante un libro de códigos, preservando sus definiciones.', 'Útil en análisis de contenido y análisis organizados por códigos. No impone un libro fijo a todas las variantes de análisis temático.', 'Si PAR reúne tanto asistencia como toma de decisiones, revisa el criterio y los fragmentos antes de comparar recuentos.', ['content']],
        'source-category': ['¿Cambian los hallazgos según la fuente o situación de producción?', 'Comparación documental con trazabilidad hacia cada fuente.', 'Apoyo transversal para diseños por casos, análisis documental y trabajo multimodal; la tabla no es un método completo.', 'Una entrevista expresa autonomía y una observación registra pedidos de autorización. Examina quién habla y en qué situación antes de hablar de contradicción.', ['framework']],
        'category-category': ['¿Qué categorías merece la pena examinar juntas?', 'Copresencia descriptiva: casos que contienen ambas categorías, aunque estén en fuentes distintas.', 'Exploración auxiliar en análisis por categorías. La copresencia puede generar preguntas, no relaciones teóricas automáticas.', 'Autonomía y Dependencia aparecen juntas: quizá describan ámbitos distintos. Busca episodios y condiciones antes de formular una explicación.', ['grounded']],
        'dimension-case': ['¿Cómo se comparan los casos según criterios interpretativos explícitos?', 'Construcción de dimensiones y reducción analítica transparente; los pesos de esta app son decisiones de quien investiga.', 'Apoyo a comparación dimensional y construcción de tipologías; no es una escala psicométrica validada.', 'Dos casos alcanzan el mismo valor por evidencias distintas. Revisa los componentes y explica por qué el eje es pertinente para tu pregunta.', ['typology']],
        typology: ['¿Puedo proponer tipos de casos con sentido y respaldo empírico?', 'Una tipología articula dimensiones de comparación y semejanzas o diferencias interpretadas.', 'Vinculada a construcción cualitativa de tipos y análisis comparativo. Los cuatro cuadrantes de la app son una ayuda gráfica, no tipos descubiertos automáticamente.', 'Un cuadrante de alta participación y baja autonomía puede sugerir participación tutelada. Contrasta casos, excepciones y evidencia antes de conservar ese nombre.', ['typology']],
        positioning: ['¿Dónde se sitúan los casos según dos criterios que puedo justificar?', 'Representación dimensional de similitudes y diferencias bajo reglas declaradas.', 'Apoyo exploratorio para comparación de casos y tipologías. No implementa una metodología de análisis del posicionamiento discursivo.', 'Si un caso queda entre dos grupos, revisa si muestra una combinación relevante o si la posición depende de pesos poco adecuados.', ['typology']],
        comparison: ['¿Qué diferencias entre grupos requieren una explicación contextual?', 'Comparación estructurada de grupos con atención a sus fuentes y condiciones.', 'Apoyo a análisis de contenido, Framework Analysis y diseños comparativos; no realiza contrastes estadísticos.', 'Más asignaciones de Colaboración en un grupo pueden reflejar entrevistas más extensas. Revisa tamaño, cobertura y significado antes de atribuir una diferencia sustantiva.', ['content']],
        network: ['¿Qué relaciones conviene explorar y cuáles puedo sostener con evidencia?', 'Una red representa vínculos definidos: copresencia, pertenencia, reglas o relaciones manuales. El tipo de vínculo determina su significado.', 'Ayuda exploratoria para organizar categorías y formular preguntas. No equivale a teoría fundamentada, análisis de redes sociales ni mapa temático reflexivo.', 'Una conexión repetida entre dos categorías invita a preguntar en qué condiciones se relacionan; un memo debe explicar el vínculo con pasajes concretos.', ['grounded', 'thematic']],
        trajectory: ['¿Cómo cambia un mismo caso entre momentos y cómo puedo explicarlo?', 'Análisis longitudinal de continuidades y cambios, distinguiendo seguimiento del caso y comparación de cortes temporales.', 'Habitual en investigación cualitativa longitudinal; requiere fuentes comparables y períodos bien definidos.', 'Un caso cambia de posición de T1 a T2. Lee qué aconteció entre momentos y comprueba si cambió la forma de entrevistar antes de atribuir el movimiento a una transformación.', ['longitudinal']],
        joint: ['¿Qué comprendo al relacionar evidencia y resultados en una misma lectura?', 'Un Joint Display facilita la integración explícita; la interpretación conjunta debe producir algo más que colocar columnas al lado.', 'Habitual en métodos mixtos. En esta app es una adaptación para codificaciones, porcentajes, fragmentos y memos; sin otro componente no constituye un diseño mixto.', 'Un recuento alto de Participación puede coexistir con relatos de escasa influencia. El memo explica esa tensión; el porcentaje solo no resuelve el sentido.', ['mixed']],
        evidence: ['¿Qué sostiene mi interpretación y dónde debo volver a revisar?', 'Trazabilidad entre afirmaciones, evidencias y decisiones de interpretación.', 'Apoyo transversal a la revisión cualitativa; no calcula saturación, calidad ni validez metodológica.', 'Un hueco en la matriz puede indicar una pregunta que no se hizo o un pasaje aún no codificado. Registra cuál de esas explicaciones encuentras al revisar.', ['thematic']]
    };
    function recommend(profile = {}) {
        const key = Object.hasOwn(approaches, profile.approach) ? profile.approach : 'unspecified';
        const entry = approaches[key];
        return { ...entry, key, label: key === 'other' && profile.customApproach ? String(profile.customApproach) : entry.label,
            picks: entry.picks.map(([type, reason]) => ({ type, reason })), refs: [...entry.refs] };
    }
    global.MethodologyGuide = Object.freeze({ references, approaches, concepts, recommend });
})(typeof window !== 'undefined' ? window : globalThis);
